<?xml version="1.0"?>
<robot name="rover" xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <!-- ================= 1. 参数定义 ================= -->
    <xacro:property name="PI" value="3.1415926"/>

    <!-- 车身尺寸 -->
    <xacro:property name="body_len" value="0.4"/>
    <xacro:property name="body_width" value="0.25"/>
    <xacro:property name="body_height" value="0.13"/>

    <!-- 车轮尺寸 -->
    <xacro:property name="length_wheel" value="0.05"/>
    <xacro:property name="radius_wheel" value="0.09" />

    <!-- 轮子位置参数 -->
    <xacro:property name="wheel_offset_x" value="0.15"/> 
    <xacro:property name="wheel_offset_y" value="0.16"/> 

    <!-- 摩擦力 (后轮保持 0.2 提供抓地力，前轮后面单独设为 0) -->
    <xacro:property name="wheel_mu" value="0.2"/>

    <!-- ================= 2. 惯性矩阵计算 ================= -->
    <xacro:macro name="box_inertial" params="m x y z">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
                     iyy="${m*(x*x+z*z)/12}" iyz="0"
                     izz="${m*(x*x+y*y)/12}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertial" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"  
                     iyy="${m*(3*r*r+h*h)/12}" iyz="0"   
                     izz="${m*r*r/2}" />
        </inertial>
    </xacro:macro>

    <!-- ================= 3. 机器人主体 ================= -->
    <link name="base_footprint">
        <visual>
            <geometry><box size="0.001 0.001 0.001"/></geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </visual>
        <xacro:box_inertial m="5.0" x="0.001" y="0.001" z="0.001"/> 
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 0.09" /> 
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>

    <link name="base_link">
        <visual>
            <geometry><box size="${body_len} ${body_width} ${body_height}"/></geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>  
            <material name="white"><color rgba="0.8 0.8 0.8 1"/></material>
        </visual>
        <collision>
            <geometry><box size="${body_len} ${body_width} ${body_height}"/></geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>  
        </collision>
        <xacro:box_inertial m="5.0" x="${body_len}" y="${body_width}" z="${body_height}"/>  
    </link>

    <!-- ================= 4. 四个轮子 ================= -->

    <!-- [1] 前左轮 (Front Left) - 从动轮 -->
    <link name="wheel_FL">
        <visual>
            <geometry>
                <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
        </visual>
        <collision>
            <geometry><cylinder length="${length_wheel}" radius="${radius_wheel}"/></geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <xacro:cylinder_inertial m="0.5" r="${radius_wheel}" h="${length_wheel}"/>
    </link>

    <joint name="joint_FL" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_FL"/>
        <origin rpy="${-PI/2} 0 0" xyz="${wheel_offset_x} ${wheel_offset_y} -0.02"/>
        <axis xyz="0 0 1" />
    </joint>

    <!-- [2] 前右轮 (Front Right) - 从动轮 -->
    <link name="wheel_FR">
        <visual>
            <geometry><cylinder length="${length_wheel}" radius="${radius_wheel}"/></geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
        </visual>
        <collision>
            <geometry><cylinder length="${length_wheel}" radius="${radius_wheel}"/></geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <xacro:cylinder_inertial m="0.5" r="${radius_wheel}" h="${length_wheel}"/>
    </link>

    <joint name="joint_FR" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_FR"/>
        <origin rpy="${-PI/2} 0 0" xyz="${wheel_offset_x} -${wheel_offset_y} -0.02"/>
        <axis xyz="0 0 1" />
    </joint>

    <!-- [3] 后左轮 (Rear Left) - 驱动轮 -->
    <link name="wheel_RL">
        <visual>
            <geometry><cylinder length="${length_wheel}" radius="${radius_wheel}"/></geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
        </visual>
        <collision>
            <geometry><cylinder length="${length_wheel}" radius="${radius_wheel}"/></geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <mu1>${wheel_mu}</mu1>
        <mu2>${wheel_mu}</mu2>
        <xacro:cylinder_inertial m="0.5" r="${radius_wheel}" h="${length_wheel}"/>
    </link>

    <joint name="joint_RL" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_RL"/>
        <origin rpy="${-PI/2} 0 0" xyz="-${wheel_offset_x} ${wheel_offset_y} -0.02"/>
        <axis xyz="0 0 1" />
    </joint>

    <!-- [4] 后右轮 (Rear Right) - 驱动轮 -->
    <link name="wheel_RR">
        <visual>
            <geometry><cylinder length="${length_wheel}" radius="${radius_wheel}"/></geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
        </visual>
        <collision>
            <geometry><cylinder length="${length_wheel}" radius="${radius_wheel}"/></geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <mu1>${wheel_mu}</mu1>
        <mu2>${wheel_mu}</mu2>
        <xacro:cylinder_inertial m="0.5" r="${radius_wheel}" h="${length_wheel}"/>
    </link>

    <joint name="joint_RR" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_RR"/>
        <origin rpy="${-PI/2} 0 0" xyz="-${wheel_offset_x} -${wheel_offset_y} -0.02"/>
        <axis xyz="0 0 1" />
    </joint>

    <!-- ================= 5. 传感器 ================= -->
    <!-- 1. 雷达支架 (Link + Joint) -->
    <link name="laserholder_link">
        <visual>
            <geometry><cylinder length="0.1" radius="0.02"/></geometry>
            <material name="green"><color rgba="0 1 0 1"/></material>
            <origin rpy="0 0 0" xyz="0 0 0.05"/>
        </visual>
        <xacro:box_inertial m="0.01" x="0.02" y="0.02" z="0.1"/>
    </link>

    <joint name="laserholder_joint" type="fixed">
        <origin xyz="0.1 0.0 0.065" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="laserholder_link"/>
    </joint>

    <!-- 2. 雷达本体 (Link + Joint) -->
    <link name="scan_link">
        <visual>
            <geometry><cylinder length="0.04" radius="0.04"/></geometry>
            <material name="blue"><color rgba="0 0 1 1"/></material>
        </visual>
        <xacro:cylinder_inertial m="0.1" r="0.04" h="0.04"/>
    </link>

    <joint name="laser_joint" type="fixed">
        <origin xyz="0.0 0.0 0.1" rpy="0 0 0"/> <!-- 装在支架顶上 -->
        <parent link="laserholder_link"/>
        <child link="scan_link"/> 
    </joint>

    <!-- 3. 雷达 Gazebo 插件  -->
    <gazebo reference="scan_link">
        <sensor name="lidar" type="ray">
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1.000000</resolution>
                        <min_angle>0.000000</min_angle>
                        <max_angle>6.280000</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.120000</min>
                    <max>10.0</max>
                    <resolution>0.02</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <remapping>~/out:=scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>scan_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>


    <!-- ================= 6. Gazebo 物理属性 & 插件 ================= -->

    <gazebo reference="wheel_FL">
        <mu1>0.5</mu1> 
        <mu2>0.001</mu2>
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="wheel_FR">
        <mu1>0.5</mu1> 
        <mu2>0.001</mu2>
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="wheel_RL"><material>Gazebo/Black</material></gazebo>
    <gazebo reference="wheel_RR"><material>Gazebo/Black</material></gazebo>
    <gazebo reference="base_link"><material>Gazebo/White</material></gazebo>

    <!-- 驱动插件 -->
    <gazebo>
        <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>
            <ros>
                <namespace>/</namespace>
                <remapping>cmd_vel:=cmd_vel</remapping>
                <remapping>odom:=odom</remapping>
            </ros>

            <left_joint>joint_RL</left_joint>
            <right_joint>joint_RR</right_joint>

            <wheel_separation>${wheel_offset_y * 2}</wheel_separation>
            <wheel_diameter>${radius_wheel * 2}</wheel_diameter>
            
            <max_wheel_torque>200</max_wheel_torque>
            <max_wheel_acceleration>5.0</max_wheel_acceleration>

            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>

            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
        </plugin>
    </gazebo>


    <gazebo>
        <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
            <ros>
                <!-- 必须重映射到标准的 /joint_states 话题 -->
                <remapping>~/out:=joint_states</remapping>
            </ros>
            <update_rate>30</update_rate>
            
            <joint_name>joint_FL</joint_name>
            <joint_name>joint_FR</joint_name>
            <joint_name>joint_RL</joint_name>
            <joint_name>joint_RR</joint_name>
        </plugin>
    </gazebo>

</robot>